if(EXISTS "/mnt/d/matapos_6_March/matapos/test/ExampleTest[1]_tests.cmake")
  include("/mnt/d/matapos_6_March/matapos/test/ExampleTest[1]_tests.cmake")
else()
  add_test(ExampleTest_NOT_BUILT ExampleTest_NOT_BUILT)
endif()
